/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ajto53j3j5hajjsgvt7ez6eiee.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ghglc4ecrjgq7gwjieg7p36qou",
    "aws_cognito_identity_pool_id": "us-east-1:eaa8d838-f798-4f62-8cbc-e1c8f393ba58",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TJZb5KwU7",
    "aws_user_pools_web_client_id": "72v5dmhmei4cnjko4k30v92sf9",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsconfig;
