SELECT * FROM ezclocker.email_template;

INSERT INTO 
	ezclocker.email_template (id, body, name, subject, version)
	VALUES (
	13,
	'<!-- TIMESHEE_HTML --><!-- Subject: [USER_NAME]''s Time Sheet --><body style="font-family: Arial, Helvetica, sans-serif; font-size:12pt"><div style="background-color: #7cd0fd; padding: 5px; border: 1px solid black; border-radius: 2px; margin: -6px;">			<table style="display: inline;"><tr><td style="text-align: left; vertical-align: middle;"><a href="https://ezclocker.com"><img src="https://ezclocker.com/public/images/logos/ezclocker_32x32.png" style="width: 32px; height: 32px; border-color: #000000; border-style: solid; border-width: 1px; margin-right: 4px; padding: 0px; , margin-bottom: auto; margin-top: auto" /></a></td><td style="font-family: monospace; font-weight: bold; font-size: 24pt; color: #000000; text-align: left; vertical-align: middle;"><a style="color: #000000; text-decoration: none" href="https://ezclocker.com">ezClocker</a></td></tr></table></div><p style="font-weight: bold;">Your employee is sharing their time sheet with you!</p><p>Attached to this email you will find a time sheet from your employee.</p><p style="font-weight: bold;">Message from employee:<br/><br/>[USER_MESSAGE]</p><p style="font-style: italic;">ezClocker is an easy to use web and mobile time tracking and scheduling app for employers and their employees. Check us out at <a href="http://www.ezclocker.com">ezclocker.com</a></p> <table style="width: 100%"><tr><td style="font-size: 12pt; padding: 8px; background-color: #ff9900; font-weight:bold;">Follow us!</td></tr><tr><td style="background-color: #e0e0e0; padding: 10px;"><a href="https://www.facebook.com/ezClocker"><img style="height: 30px; width: 30px;" src="http://api.ning.com/files/yK4NcMrBlofWleqeABbNHR-JwhBMxMRlC7NRM0KCYhLk4i-pqoO0AYXzAp3bKHf0IYIP3Qjn0GVzm5V1Gv56dUqaq68hdmSW/facebooks1_60.png"/></a>		<a href="https://twitter.com/ezClocker"><img style="height: 30px; width: 30px; margin-left: 10px;" src="http://api.ning.com/files/vwYvIcXARnCDb7rmTyv-ajyO2kvmHyKJ813N8CvFCImegtIaEvi9NeRhZ1RWCqojSEvAqmOzVNsoWX4HPus6Zwt-nMYOBXWU/twitters1_60.png"/></a></td></tr></table></body>',
	'TIMESHEE_HTML2',
	'[USER_NAME]''s Time Sheet',
	0);